# This is a generated file. Not intended for manual editing.
services:
  dockerdebugissue:
    build:
      context: "C:\\Projects\\DockerDebugIssue"
      dockerfile: "DockerDebugIssue/Dockerfile"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "dockerdebugissue:dev"
    ports:
    - "57003:57100"
    - "57203:57300"
    volumes:
    - "C:\\Projects\\DockerDebugIssue\\DockerDebugIssue:/app:rw"
    - "C:\\Users\\aleksei.smirnov\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2023.1.2\\Linux64:/riderDebugger"
    - "C:\\Users\\aleksei.smirnov\\AppData\\Local\\JetBrains\\Toolbox\\apps\\Rider\\\
      ch-0\\231.9011.39/bin:/riderLogsConf"
    - "C:\\Users\\aleksei.smirnov\\AppData\\Local\\JetBrains\\Rider2023.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_6_06_14_34_18:/riderLogs:rw"
    working_dir: "/app"
